### ISSUE TITLE
Debug Info being printed

### ISSUE THREAD

**Issue by ghost** [deimos-deimos/comfy_api_simplified#5]
Great wrapper, only small annoyance is the print statement for the response that seems to be backed in (/tree/main/comfy_api_simplified/comfy_api_wrapper.py line 80). Would be nice if it was removed or switchable (or only triggered if there is an actual error to report).

**Comment by deimos-deimos** [comment]
Fixed in 1.1.2
https://pypi.org/manage/project/comfy-api-simplified/release/1.1.2/
